name = "DICEModel"
uuid = "a78ebace-d296-4f52-9067-75f12fe9a0bd"
authors = ["Antonello Lobianco <antonello@lobianco.org>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
DocStringExtensions = "0.9.3"
Ipopt = "1.4"
JuMP = "1.20"
PrecompileTools = "1"
julia = "1.7"
